package com.nandhini.project.expense_tracker.expense_app;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDate;

//Data layer
@Entity //Marks this class as a JPA entity that will be mapped to a database table.
public class ExpenseTracker {

    @Id //to tell which is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //consecutive value is generated by default.
    private int id;

    private String username;

    private double amount;

    private String description;

    //@Column(name=Currency) - for giving column name
    private String currency;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate date;

    //no-parameter constructor - will be helpful when creating empty objects.
    public ExpenseTracker(){
    }

    //constructor for assigning values.
    public ExpenseTracker(double amount, String description, int id, String name, LocalDate date, String currency) {
        this.amount = amount;
        this.description = description;
        this.id = id;
        this.username = name;
        this.date = date;
        this.currency = currency;
    }

    //getters and setters
    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return username;
    }

    public void setName(String name) {
        this.username = name;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public LocalDate getDate() { return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "ExpenseTracker{" +
                "amount=" + amount +
                ", id='" + id + '\'' +
                ", username='" + username + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}

